version: "3.8"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  leaderboard-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
